main3.native: main3.ml
	ocamlbuild -use-ocamlfind main3.native -tag annot

main2.native: main2.ml
	ocamlbuild -use-ocamlfind main2.native -tag annot

main.native: main.ml
	ocamlbuild -use-ocamlfind main.native -tag annot

clean:
	ocamlbuild -clean
